<!--<link href="<?=$this->baseUrl('calendario/jquery-ui.css')?>" rel="stylesheet" type="text/css"/>
  <script src="<?=$this->baseUrl('calendario/jquery.min.js')?>"></script>
  <script src="<?=$this->baseUrl('calendario/jquery-ui.min.js')?>"></script>
  <script src="<?=$this->baseUrl('calendario/jquery.ui.datepicker-pt-BR.js')?>"></script>
  <script>
  $(document).ready(function() {
    $("#data_nasciment0").datepicker();
    $("#data_nascimento").datepicker($.datepicker.regional['pt-BR']);
    
  });
 

  
  </script>-->

              
  <div style="margin-top:-200px;width: 500px;height: 500px" class="modal">
                <br/>
                <div style="margin-left: 10px;margin-top: 20px;font-size: 20px;color: #0081c2">Para realizar o cadastro, preencha os dados e clique em cadastrar.</div>
                <br/>
                 <?=$this->form?>
   </div>