<div style="margin-left: 10%;border: 1px solid #B8B8B8;border-radius: 5px;margin-top:70px;width: 1000px;height: 660px" class="">
                
    <br/>
                <div style="float: left; margin-left: 10px;margin-top: 20px;font-size: 20px;color: #0081c2">
                    <div class="foto" ></div>
                    <div style="margin-top: 13px;">Nome: Marcelo Maia Lopes</div>
                     <div style="margin-top: 8px;">Email: marcelomaialopes@yahoo.com.br</div>
                    <div style="margin-top: 8px;">Data de nascimento: 19/12/1122</div>
                    <button style="margin-top: 20px;"  class="btn btn-large btn-primary" type="button">Editar meus dados</button>
                 </div>
                
                <div style="margin-left: 400px;width: 550px;height: 500px;">
                    <div style="font-size: 20px;color: #0081c2">Para cadastrar uma notícia, preencha o formulário.</div>
<!--                    <form style="margin-left: 10px;margin-top: 30px">
                      
                        <input class="input-xxlarge" type="text" placeholder="Titulo da noticia">
                        <input title="Inserir imagem relacionada a noticia" type="file"/>
                        <div style="margin-top: 8px"></div>
                        <select class="span2">
                            <option value="1">Categoria</option>
                            <option value="universidade">Universidade</option>
                            <option value="cidades">Cidade</option>
                            <option value="politica">Politica</option>
                            <option value="entretenimento">Entretenimento</option>
                            <option value="outros">Outros</option>
                        </select>
                   
                        <textarea placeholder="Digite a descrição de sua noticia." style="width: 400px"  rows="12" ></textarea>
                       <button class="btn btn-large btn" type="button">Cadastrar notícia</button>
                    </form>-->
                
                    <?=$this->form?>
                
                </div>
                  
                  
                
                <br/>
                 
   </div>